### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by strk** [bromix/plugin.video.youtube#123]
Attempts to search trigger a failure. here's the log snippet:

13:49:56 T:3079423792  NOTICE: ES: Starting event server
13:49:56 T:3079423792   ERROR: JSONRPC Server: Failed to connect to sdpd
13:49:56 T:3079423792  NOTICE: starting zeroconf publishing
13:49:56 T:2844576624  NOTICE: Thread CEventServer start, auto delete: false
13:49:56 T:2844576624  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
13:49:56 T:2844576624  NOTICE: UDP: Listening on port 9777
13:49:56 T:2836183920  NOTICE: Thread CTCPServer start, auto delete: false
13:49:56 T:2827791216  NOTICE: Thread Jobworker start, auto delete: true
13:49:56 T:3069295472  NOTICE: Thread CRssReader start, auto delete: false
13:50:08 T:2844576624  NOTICE: ES: Incoming connection from Android XBMC Remote
13:50:10 T:2928409456  NOTICE: Thread Background Loader start, auto delete: false
13:50:12 T:2928409456  NOTICE: Thread Jobworker start, auto delete: true
13:50:18 T:3035626352  NOTICE: Thread XBPyThread start, auto delete: false
13:50:18 T:3035626352  NOTICE: -->Python Interpreter Initialized<--
13:50:19 T:3035626352   ERROR: close failed in file object destructor:
13:50:19 T:3035626352   ERROR: IOError
13:50:19 T:3035626352   ERROR: :
13:50:19 T:3035626352   ERROR: [Errno 10] No child processes

Ideas on how to fix ? Is this a setup issue ? This is with xmbc 12.2

**Comment by bromix** [comment]
Sorry, but I can't support Frodo anymore. The API of the Python-Interpreter + the old Python xbmc API (xbmcgui, xbmcaddon...) makes maintaining the Addon more compljcatedcomplicated.

**Comment by strk** [comment]
is there any older version / tag that works on frodo and current youtube service ?

**Comment by bromix** [comment]
Only the old YouTube addon. But this will only work till May 2015 because of the shutdown of the APIv2 by Google. You should consider an update at least to Gotham.
