### ISSUE TITLE
Update subscriptionpage

### ISSUE THREAD

**Issue by Cnuut** [bromix/plugin.video.youtube#134]
Thanks for this very nice youtube script/app!
I would really like to have a update feature on the subscription page, instead of having to go back and then in again.
And a thumbnail view with media info on the side with scrollable description would be awesome.
Thanks again for this 5.x
:)

**Comment by bromix** [comment]
Thanks :)
I could add an 'Update' or 'Refresh' menu item in the context menu for the subscriptions. But I don't know if the steps would me less then going forth and back.

For the thumbnail view with media info, this is depending on the skin you're using.

**Comment by Cnuut** [comment]
Well this version is working better then previous one, so its pretty fast going back & forth on the raspberry pie (OSMC) but it would be nice with a update/refresh thing in the subscription page. And don`t worry I noticed the Amber skin had a version for Kodi :)

**Comment by Cnuut** [comment]
Hi really nice! But I use my TV remote (CEC) to navigate Kodi and there is no possibility to right click with that so it would be cool if there was some way to have the refresh as a "thumbnailbox" like the [..] is this at all possible? :)

**Comment by bromix** [comment]
Sorry no...this would mean I have to add dummy items with real functions behind it even though it would be possible via remote and the context menu. It would mean you have to navigate to this item...at this point I see no benefit compared to go back and re-enter 'My Subscriptions'

**Comment by Cnuut** [comment]
ok thanks for the reply! :)
