### ISSUE TITLE
2160p support

### ISSUE THREAD

**Issue by martell** [bromix/plugin.video.youtube#139]
Hi,
looking at 
/resources/lib/youtube/helper/video_info.py
The formats for 4k are missing.

I could do a PR for this but what happens if the user doesn't have 4k.

Settings should be able to set quality to 720p 1080p 2160p not using high and words like full hd as they are confusing and do not specifically specify a resolution

Thoughts ?

**Comment by bromix** [comment]
Won't work because of DASH (separated video and audio streams) which KODI/XBMC doesn't support. Therfore only up to 720p will work and only 1080p in rare cases for livestreams.

**Comment by bromix** [comment]
New names will come for the resolution because some people seem really don't know the names by definition ;)

**Comment by martell** [comment]
Hmm after reading some more i see the issue with the adaptive DASH player.

You still have code however for 1080p support so wouldn't it be easy to add 2160p to it in the same manner.

Who knows maybe we will get a 4k live stream sometime this year :)
 
I have been looking at how to disable dash and a few chrome and firefox plugins seem to be able to do this. I think this plugin would be able to do the same as we are essentially just a client.
Sorry to lean off topic. I'm trying to learn more about the blocker

**Comment by bromix** [comment]
See Issue: https://github.com/bromix/kodion/issues/35
I'm using my own kind of framework :) so SD, HD and Full HD will become 240p, 360p, 480p, 720p and 1080p in one of the next updates.

This would be cool to play 1080p without dash ;) let me know if you found something ^^

**Comment by martell** [comment]
1080p in one of the next updates?
Are you using some sort of flash interpreter ?
Or have you added some support for the dash protocol.

1080p without dash doesn't seem possible anymore, even in those plugins :/

**Comment by bromix** [comment]
Nono ;) 1080p I provide only in case of live streams...these don't use DASH...all other videos will only work with 720p.

**Comment by martell** [comment]
http://youtube-eng.blogspot.jp/2015/01/youtube-now-defaults-to-html5_27.html
It should be possible now right?
Flash is no longer used so html5 should offer all the resolutions.

**Comment by bromix** [comment]
Its still the same thing ;) DASH via flash in now DASH via html5+extension tag. It changes nothing because KODI doesn't supports it.

**Comment by martell** [comment]
Damn :D 
So does this mean google now only use DASH ?
As in do we still have 720p set streams

**Comment by bromix** [comment]
Only for higher resolution, but for more infos please read here:
http://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP

Between 720p and 1080p you won't see much of difference - the bitrate is for 1080p quite low.

**Comment by Queuecumber** [comment]
Has there been any movement on DASH support from the Kodi side since this was brought up?
