### ISSUE TITLE
YouTube Video Download - finished

### ISSUE THREAD

**Issue by rdissertori** [bromix/plugin.video.youtube#140]
Hello,

I've finished a fully working implementation to be able to download youtube videos via the context menu.
When I get back from work tonight, I will post a link to the sources.

Just beforehand:
It's fully modular and well integrated into your addon, but I will post more information tonight (gmt+1)
I'm sure you will like it and use it for your repository.

Cheers _moo_

**Comment by bromix** [comment]
Sorry, but at the current state I won't risk any further updates of the (main) addon because of a download feature. See comment of one of the KODI devs. I'm in contact with.
http://forum.kodi.tv/showthread.php?tid=200735&pid=1871638#pid1871638

**Comment by rdissertori** [comment]
ok thanks for the reply and the link you provided to clarify this. I guess it's kist fine if I continue this on my inofficial repository then (for my relatives). Anyways thumbs up for all the work so far!

**Comment by uNiversaI** [comment]
>Sorry, but at the current state I won't risk any further updates of the (main) addon because of a download feature. See comment of one of the KODI devs. I'm in contact with.
http://forum.kodi.tv/showthread.php?tid=200735&pid=1871638#pid1871638

I disagree that kodi devs should dictate / influence progress of this addon. quite sad.
