### ISSUE TITLE
Live streams doesn't work

### ISSUE THREAD

**Issue by th--** [bromix/plugin.video.youtube#149]
When i try to play live stream, nothing happening.

**Comment by bromix** [comment]
A little more information would be nice don't you think?
I can't fix your problem because the lag of information.

Which Video, full log via pastebin.com or similar.

**Comment by th--** [comment]
When i play any live video stream from Youtube, i have an error in log file:
http://fpaste.org/169907/30923214/

**Comment by bromix** [comment]
Works like a charm for me. http://i.imgur.com/DQALjrq.png
Can you provide me with a **FULL** (I already mentioned) log :)

**Comment by th--** [comment]
"Works like a charm for me."
Because it's not "live" anymore at this moment.

Here a FULL log file:
http://fpaste.org/170698/21440570/

**Comment by bromix** [comment]
I don't know what else I can show you :)
http://i.imgur.com/IFASmWr.png

At the current state the video is live...left YouTube...Middle KODI and right my local time.

And the second video 'Na...girl...room' isn't available anymore.

**Comment by th--** [comment]
I don't know, last what i try - "France24 live news". 
Maybe it's work, because you use windows versin of KODI... I have RaspBMC KODI and Android versions, and it's dosent work.
Log from Android clean installation KODI + youtube plugin:
http://fpaste.org/171061/58046914

**Comment by bromix** [comment]
I see. Tested on my Android. KODI isn't supporting the format of the live-stream. The demuxer is failing. If I can't get another format then Android (arm) systems aren't supported for live streams.

**Comment by soduntan** [comment]
@bromix I am having the same issue on my Android box.  Do you know when you will be able to get a fix for this?  Thanks.

**Comment by bromix** [comment]
@soduntan I don't know if I could fix this. The binary of XBMC/KODI for Android support TS-Streams very well or not at all. If this isn't provided I can't do anything.

**Comment by soduntan** [comment]
@bromix Thanks for the prompt feedback.  Please let me know what you find.  Keep up the great work!!!

**Comment by carlosedp** [comment]
Coachella live streams also do not work. Tried this weekend.

**Comment by bromix** [comment]
URL out video + debug log would help ;)
