### ISSUE TITLE
Italian translations

### ISSUE THREAD

**Issue by NeverWise** [bromix/plugin.video.youtube#161]
Some italian translations are wrong. I'm Italian, If you want I can correct it for you?

**Comment by bromix** [comment]
If you want, you're welcome :)

**Comment by NeverWise** [comment]
how can i do?
fork the project and after made the changes push to you a request to merge...

**Comment by bromix** [comment]
Yes...this would do it :)

**Comment by bromix** [comment]
Thanks ;)
