### ISSUE TITLE
Stopping HD videos blocks everything

### ISSUE THREAD

**Issue by gillesfernandez** [bromix/plugin.video.youtube#163]
Hello bromix,

I've been trying to watch videos in HD, everything works perfectly fine (playing, pausing,...). But, when I stop the video, everything is blocked, kodi uses 100% of CPU and after 4-5 minutes it is still blocked.

I've tried SD videos, it takes 4-5 seconds to stop but it works.

I've tried to get debug information but it doesn't say anything. On the previous youtube plugin (kodi repo), I have the same bug and I get this message :
```
Exception AttributeError: "type object 'AbstractLogger' has no attribute '__del__'" in <bound method XbmcLogger.__del__ of <resources.lib.kodion.impl.xbmc.xbmc_logger.XbmcLogger object at 0xb0618230>> ignored
Exception AttributeError: "type object 'AbstractLogger' has no attribute '__del__'" in <bound method XbmcLogger.__del__ of <resources.lib.kodion.impl.xbmc.xbmc_logger.XbmcLogger object at 0xac287b10>> ignored
Exception AttributeError: "type object 'AbstractLogger' has no attribute '__del__'" in <bound method XbmcLogger.__del__ of <resources.lib.kodion.impl.xbmc.xbmc_logger.XbmcLogger object at 0xb06444b0>> ignored
Exception AttributeError: "type object 'AbstractLogger' has no attribute '__del__'" in <bound method XbmcLogger.__del__ of <resources.lib.kodion.impl.xbmc.xbmc_logger.XbmcLogger object at 0xa7cf3d30>> ignored
```
Here is the video I used to make my tests : https://www.youtube.com/watch?v=lb-oHOu3igg

I am on Kodi 14 (Helix) on an Ubuntu Linaro. I haven't tested on another platform currently but I could.

I know I don't have a lot of debug information, if you want me to test a more focus aspect, I'll do all I can to help.

**Comment by bromix** [comment]
mhmm....can you provide me with the complete log? This should be fixed with 5.0.4 but I will test this again :)

**Comment by gillesfernandez** [comment]
I've juste tested with 5.0.4 and I got this :
Test 1 :
- Playing the video
- Stoping the video
- The video stops normally, everything seems to work fine
- Playing the video again
- Stoping the video again
- Bug happens

Test 2 :
- Playing the video
- Stoping the video
- Bug happens

Here is the full log file with debug mode activated for video and audio (this is the Test 2) : http://pastebin.com/ygrhDmEK

**Comment by bromix** [comment]
16:23:02 T:3035448320  NOTICE: Disabled debug logging due to GUI setting. Level 0.

Debug was disabled. I can see no error at all. Can you try it again with debug activated?

**Comment by gillesfernandez** [comment]
Is it better like this? http://pastebin.com/HmVDnZ5y

Sorry, I'm discovering xbmc debugging...

**Comment by bromix** [comment]
No problem ;)

Can you at least update KODI to 14.0. You're working with an old alpha version. Maybe this will resolve the problem ;)

**Comment by bromix** [comment]
See #171 
The problem seems to be that on unix systems WEBM-Container are not supported well like MP4-Container - nevertheless a MP4-Container would be preferred.

**Comment by gillesfernandez** [comment]
Sorry for the delay, I had to recompile kodi and encoutered a few problems...
The bug is still the same on Kodi 14.0.

If I understand well the #171 thread, it should be resolved in 5.0.6? I'll try to update today or tomorrow and test it.

**Comment by bromix** [comment]
Maybe...this will be the next version of the addon. Someone gave me a hint that some containers are not well support on a unix system (WEBM for example). So I will try to filter the container I now of. I hope what works for the normal videos will work for the live streams as well.

**Comment by bromix** [comment]
I changed something in the selection of the stream in 5.0.6~beta2...maybe this will change something?

**Comment by gillesfernandez** [comment]
Thank you for the update, I'll try it as soon as possible.

**Comment by bromix** [comment]
I close this one...if there is any trouble, feel free to reopen.
