### ISSUE TITLE
VEVO not playing

### ISSUE THREAD

**Issue by bromix** [bromix/plugin.video.youtube#167]

**Comment by bromix** [comment]
5136aa28c472d12bdda68c40c55b1dc33bcb33f4

**Comment by Notmarrco** [comment]
Hi,
It seems to me that VEVO is broken again, since today or yesterday  I'd say. :) 
Is there a quick fix I could use ?
thx

**Comment by bromix** [comment]
How about an example of the video ;) I can't guess the video...here everything is working fine.

**Comment by bromix** [comment]
See https://github.com/bromix/plugin.video.youtube/commit/7be99bf7a33cef6b27a6e31781778de1b0cf742d
this should maybe fix the problem (based on the information in http://forum.kodi.tv)
