### ISSUE TITLE
Use of deprecated youtube link

### ISSUE THREAD

**Issue by bajo** [bromix/plugin.video.youtube#181]
In my log files with version 5.0.4 and 5.0.5 I get the following warnings.

``18:37:42 T:139893118252800 WARNING: [plugin.video.youtube] DEPRECATED "plugin://plugin.video.youtube/?action=play_video&videoid=oh2LWWORoiM"``
``18:37:42 T:139893118252800 WARNING: [plugin.video.youtube] USE INSTEAD "plugin://plugin.video.youtube/play/?video_id=oh2LWWORoiM"``

Is this something that needs taking care of in the near future?

**Comment by bromix** [comment]
Yes...I think till the end of this year when the next version of KODI will be released. I also have to talk to the developer of Yatse so he will adjust the URIs.
