### ISSUE TITLE
Extract additional video, playlist and user IDs from the description

### ISSUE THREAD

**Issue by bromix** [bromix/plugin.video.youtube#187]
Most video descriptions provide links to additional videos. Maybe we can extract them and provide them for navigation.

**Comment by bromix** [comment]
We provide an item in the context menu if we find video links in the description.
'Videos from Description'

**Comment by freeman212** [comment]
that's amazing!

**Comment by bromix** [comment]
WIth the commit https://github.com/bromix/plugin.video.youtube/commit/231f6c7a31d0404542da9cb8401e9025a1a8d046 some basic stuff like videos, playlists and simple channels can be extracted. Channels based on the username aren't working yet.

**Comment by bromix** [comment]
Finished with https://github.com/bromix/plugin.video.youtube/commit/627b9222ba749c5a979aad61963ccfce7010c5d0

**Comment by bromix** [comment]
Found a bug with the following video:
https://www.youtube.com/watch?v=jv9MX7Kj3NY

**Comment by bromix** [comment]
Create 2 new issues out of this #231 and #232
