### ISSUE TITLE
Show channel name in "My subscriptions" list view

### ISSUE THREAD

**Issue by marank** [bromix/plugin.video.youtube#189]
It would be nice to see the channel name for every video in the standard list view, e.g. append it to the date in the second line.

**Comment by bromix** [comment]
Can you clarify :) do you mean for each video item?
ChannelName - VideoTitle?

**Comment by marank** [comment]
Currently, it looks like this (using the 1080XF skin): http://i.imgur.com/Keo4mSe.jpg
Maybe you can put the channel name for each video entry after its respective upload date, so for example: "12.02.2015 - Channel Name".
Hope I've explained it good enough :)

**Comment by bromix** [comment]
Ahhh...in this case I would ask the developer of the skin. Because I provide channelnames via the Studio-Info-Label and I have seen other skins using this information.
LineBreaks are not a good solution for this.

**Comment by marank** [comment]
All right, thanks for pointing this out and sorry for opening an issue for this :)
