### ISSUE TITLE
plugin stopped working

### ISSUE THREAD

**Issue by Dikay900** [bromix/plugin.video.youtube#195]
yesterday the plugin did not work anymore and since it seems noone has reported this yet i want to do so.

i hope this is the correct place.

extract of kodi.log:
https://gist.github.com/Dikay900/f8822a812bb750643683

simple as what i did just go into the plugin, select any video, systems seems to load the stream and then it fails.

**Comment by bromix** [comment]
Work fine here ;) did you test the 5.0.6~beta?

**Comment by Dikay900** [comment]
yeah just found your forums post on kodi.tv unfortunately it seems its a problem on my end...
i just added your repository from http://forum.kodi.tv/showthread.php?tid=200295 but the list is empty on my system :/

**Comment by Dikay900** [comment]
think we can close this, i think i have a problem with my system.
keep up the great work :+1:
