### ISSUE TITLE
[playback] video won't play

### ISSUE THREAD

**Issue by bromix** [bromix/plugin.video.youtube#199]
Video won't play?
id=ZDX8SoYMizA

http://forum.kodi.tv/showthread.php?tid=200735&pid=1930980#pid1930980

**Comment by bromix** [comment]
And also this one:
http://forum.kodi.tv/showthread.php?tid=200735&pid=1931963#pid1931963

the 'itag' is missing

**Comment by Dikay900** [comment]
hi there its me again since i cannot get youtube to get working (having same issues and same log as mentioned in these posts)

You already resolved this issue cause its closed? Asking because i don't see a commit for this.

**Comment by bromix** [comment]
Have you tested v5.0.7-beta1?
I can't reproduce any of the logs :(

**Comment by Dikay900** [comment]
i have tested this version too but that did not resolve the issue. It seems like this is a problem of the xbian distro. the log above is also from this distro maybe i just wait for another release of them. So i think there is nothing to do on your side.
