### ISSUE TITLE
Unsubscribe in 'My subscription'

### ISSUE THREAD

**Issue by bromix** [bromix/plugin.video.youtube#213]
Based on the logic, every video under 'My Subscription' is from a subscribed channel. So we can show 'Unsubscribe' instead of 'subscribe'

**Comment by bromix** [comment]
God dammit YouTube (Google)...can you do anything right. Subscription IDs differ from channel IDs...so I have not the chance (without losing performance) to know MY subscription IDs for a channel. Man...vimeo has done everything right.

**Comment by freeman212** [comment]
ahh shame on you, Google! (big up Vimeo, I knew you guys are doing a great job)

**Comment by bromix** [comment]
:+1:

**Comment by bromix** [comment]
:D
