### ISSUE TITLE
Add ability to increase cache size

### ISSUE THREAD

**Issue by pecet** [bromix/plugin.video.youtube#239]
Hi. Could you add ability to increase video buffer size? Would help to those with not so good internet and lot of RAM to use. I would like to increase size size to 100 mb or more if possible.

Also even when it's set to 20MB, when using debug info on kodi I see "cache:10mb" as maximum value on Raspberry Pi 2 on OpenELEC.

**Comment by bromix** [comment]
Has nothing to do with video. The cache is for data only.
