### ISSUE TITLE
fanart and icon updates.

### ISSUE THREAD

**Issue by uNiversaI** [bromix/plugin.video.youtube#240]
Ive had them for a while and was put off from submitting them via PR because its confusing development process and you never have one point where to submit one PR.

I'm not going to open any PR's and chase @bromix around, So do what you will with this or dont do anything. The work is here and is done.

If you have reasonable suggestions, I'm open to suggestions but based on last feedback this was what was indicated.

fanart (same as cureent simple and nice but no pixelation. 1280x720
![fanart](https://cloud.githubusercontent.com/assets/3521959/7127155/055a6bd4-e238-11e4-9f51-ccff223bad4a.jpg)

Icon Slightly better format and reads better in kodi. 256x256
![icon](https://cloud.githubusercontent.com/assets/3521959/7127154/05589656-e238-11e4-85a9-79327c82a74a.png)

**Comment by bromix** [comment]
Looks really nice. If it's okay with you I include your changes in the final 5.1.0?

**Comment by uNiversaI** [comment]
Sure, use away and enjoy. Ive been using it already :)

**Comment by bromix** [comment]
Inlcuded :)
