### ISSUE TITLE
Youtube Pairing

### ISSUE THREAD

**Issue by garypower** [bromix/plugin.video.youtube#244]
Hey guys, love the app just wondering have you any plans to include "connected TV's" feature in the app. I have version 5.0.9 and its great it is just Airplay streaming is broken and this would be a good workaround. 

https://www.youtube.com/pair

Looking at the API to see if there was anything I could contribute.

**Comment by bromix** [comment]
Nope sorry...to complicated ;) You have to run a local server for the commands to receive from the YouTube-Server (each command of yours runs first through the server of YouTube before reaching your device) - in case of KODI an additional addon running as services would be needed.
