### ISSUE TITLE
Youtube device support warning

### ISSUE THREAD

**Issue by JohnMcLear** [bromix/plugin.video.youtube#246]
This might be the wrong place for this but youtube have been injecting device support warning into subscription feeds that use this plugin.

The file "https -_youtube.com_devicesupport.mp4" appears to warn that due to a Youtube API change this feed will no longer work.

Is this plugin ready for the change?

**Comment by evaryont** [comment]
Getting it myself as well. The video itself isn't particularly helpful in describing exactly *what* changed, just a 3:55 minute video mentioning (in a large multitude of languages):

![screenshot002](https://cloud.githubusercontent.com/assets/14547/7266391/ad84fa06-e85d-11e4-9964-c1163e4df364.png)

> Youtube is upgrading to a newer version, which is not supported by this device or app. To learn more and see where you can watch Youtube, visit www.youtube.com/devicesupport

**Comment by bromix** [comment]
Already on it ;) beta12 is a test with an alternative implementation. Nothing to worry.

**Comment by JohnMcLear** [comment]
@bromix is the man, thanks buddy :)  Would you like me to checkout beta12 and test or sit tight?

**Comment by bromix** [comment]
@JohnMcLear yes, would be cool the gather more feedback on this :)

**Comment by JohnMcLear** [comment]
Okay I will checkout today and test tonight

**Comment by sigmap** [comment]
Can we grab the beta without affecting the default plugin?

**Comment by bromix** [comment]
If you're already using the v5.0.X version of the addon, there shouldn't be any problem. But I think I will release this version tonight :)

**Comment by MilhouseVH** [comment]
I'm on 5.1.3 of the addon, but getting a YouTube API warning ("You're using old YouTube-Plugin calls") in Kai toast when viewing trailers from Confluence -> Movie Info panel...

Example (latest OpenELEC/Kodi master on RPi2):
```
00:30:06 5541.152344 T:1967726592   DEBUG: StartScript - calling plugin YouTube('plugin://plugin.video.youtube/','4','?action=play_video&videoid=eaUAUcIZS24')
00:30:06 5541.153320 T:1814385728   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/default.py): start processing
00:30:06 5541.279297 T:1814385728   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.youtube/default.py"
00:30:06 5541.279297 T:1814385728   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.youtube:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
00:30:06 5541.279297 T:1814385728   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/default.py): entering source directory /storage/.kodi/addons/plugin.video.youtube
00:30:06 5541.279785 T:1814385728   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/default.py): instantiating addon using automatically obtained id of "plugin.video.youtube" dependent on version 2.14.0 of the xbmc.python api
00:30:06 5541.572754 T:1814385728   DEBUG: [plugin.video.youtube] Starting Kodion framework by bromix...
00:30:06 5541.625488 T:1814385728  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.3) on Isengard (15.0) with Python 2.7.3
00:30:06 5541.626465 T:1814385728   DEBUG: [plugin.video.youtube] Path: "/
00:30:06 5541.626465 T:1814385728   DEBUG: [plugin.video.youtube] Params: "{'action': u'play_video', 'videoid': u'eaUAUcIZS24'}"
00:30:06 5541.664062 T:1814385728 WARNING: [plugin.video.youtube] DEPRECATED "plugin://plugin.video.youtube/?action=play_video&videoid=eaUAUcIZS24"
00:30:06 5541.664551 T:1814385728 WARNING: [plugin.video.youtube] USE INSTEAD "plugin://plugin.video.youtube/play/?video_id=eaUAUcIZS24"
00:30:06 5541.707520 T:1814385728   DEBUG: [plugin.video.youtube] Selecting YouTube config "Isengard"
```
Is this resolved by the beta?

**Comment by bromix** [comment]
It's a complete different problem. You're using Isengard right? Starting with Isengaed I will drop the old Endpoints. Either the skin or some scraper is using endpoints prior to version 5.x

**Comment by MilhouseVH** [comment]
OK thanks, yes it's Isengard - top of tree master. The YouTube trailer urls are set by Ember Media manager in my movie NFOs - hopefully if the urls are in the "old" format it will be possible fur the add-on to dynamically convert them to the new format, rather than have to update every NFO and rescrape etc.

**Comment by bromix** [comment]
No. With Isengard I stop the support for the old endpoints (urls). The old urls are a mess. Contact a dev. of the Ember Media Manager to correct the urls.

**Comment by MilhouseVH** [comment]
The problem is the historical information users will have in their libraries, you're expecting everyone to be able to update their existing library information to the new format which is probably unrealistic. I'm sure Ember will sort themselves out going forward, which is fine for new movies that are added in future, but you're still going to have problems with users and their existing libraries full of the old urls.

Looking at the example above it would seem fairly trivial to convert that on-the-fly, although I fully understand there may be more complicated examples. It's no big deal to me personally if you don't provide a solution for these old urls as I rarely use the trailers feature and just thought I'd mention it as I'd noticed it, but I suspect this will become more of an issue for other users in the future.

**Comment by mkortstiege** [comment]
It's not just 3rd party. It's pretty much every scraper that is using commons from our themoviedb scraper (and others). Is there a chance to disable the toast and to further support of the old plugin URL schema?
