### ISSUE TITLE
Add support "Connected TVs" 

### ISSUE THREAD

**Issue by tyjtyj** [bromix/plugin.video.youtube#251]
On android there is function to add connected TVs in setting, These works with major TV maker eg LG, Samsung. 

I would like to see this able to work with Kodi YouTube plugin will be great

**Comment by bromix** [comment]
Sorry, but the protocol is complicated and we need a service running on KODI :) which will collect the commands (they come from the Server, not internally from your LAN) to relay them to the addon.

I already looked into it, but this would be another project and the time spent is in my opinion not worth it. If you have an Android use Yatse...it can do even more ;)
