### ISSUE TITLE
Update too long while l load playlist

### ISSUE THREAD

**Issue by derf974** [bromix/plugin.video.youtube#264]
First, sorry for my english.
I have somes issues when i want to load a playlist.
It's stays at  0%.
For information, everything works while I want to read a video.

**Comment by bromix** [comment]
Please provide a complete debug log.

**Comment by derf974** [comment]
﻿20:48:08 T:3038232576  NOTICE: special://profile/ is mapped to: special://masterprofile/
20:48:08 T:3038232576  NOTICE: -----------------------------------------------------------------------
20:48:08 T:3038232576  NOTICE: Starting Kodi (14.1 Git:2015-02-02-81c4046-dirty). Platform: Linux ARM 32-bit
20:48:08 T:3038232576  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
20:48:08 T:3038232576  NOTICE: Kodi compiled Feb  2 2015 by GCC 4.7.1 for Linux ARM 32-bit version 3.2.21 (197141)
20:48:08 T:3038232576  NOTICE: Running on Raspbian GNU/Linux 7 (wheezy), kernel: Linux ARM 32-bit version 3.12.34+
20:48:08 T:3038232576  NOTICE: FFmpeg statically linked, version: Frodo_alpha5-14025-g81c4046-xbmc-2.4.6-Helix
20:48:08 T:3038232576  NOTICE: Host CPU: ARMv6-compatible processor rev 7 (v6l), 1 core available
20:48:08 T:3038232576  NOTICE: ARM Features: Neon disabled
20:48:08 T:3038232576  NOTICE: special://xbmc/ is mapped to: /opt/xbmc-bcm/xbmc-bin/share/xbmc
20:48:08 T:3038232576  NOTICE: special://xbmcbin/ is mapped to: /opt/xbmc-bcm/xbmc-bin/lib/kodi
20:48:08 T:3038232576  NOTICE: special://masterprofile/ is mapped to: /home/pi/.kodi/userdata
20:48:08 T:3038232576  NOTICE: special://home/ is mapped to: /home/pi/.kodi
20:48:08 T:3038232576  NOTICE: special://temp/ is mapped to: /home/pi/.kodi/temp
20:48:08 T:3038232576  NOTICE: The executable running is: /opt/xbmc-bcm/xbmc-bin/lib/kodi/kodi.bin
20:48:08 T:3038232576  NOTICE: Local hostname: raspbmc
20:48:08 T:3038232576  NOTICE: Log File is located: /home/pi/.kodi/temp/kodi.log
20:48:08 T:3038232576  NOTICE: -----------------------------------------------------------------------
20:48:09 T:3038232576  NOTICE: load settings...
20:48:09 T:3038232576  NOTICE: Found 1 Lists of Devices
20:48:09 T:3038232576  NOTICE: Enumerated PI devices:
20:48:09 T:3038232576  NOTICE:     Device 1
20:48:09 T:3038232576  NOTICE:         m_deviceName      : HDMI
20:48:09 T:3038232576  NOTICE:         m_displayName     : HDMI
20:48:09 T:3038232576  NOTICE:         m_displayNameExtra:
20:48:09 T:3038232576  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
20:48:09 T:3038232576  NOTICE:         m_channels        : FL,FR
20:48:09 T:3038232576  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,24000,32000,44100,48000,88200,96000,176400,192000
20:48:09 T:3038232576  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP,AE_FMT_AC3,AE_FMT_DTS,AE_FMT_EAC3
20:48:09 T:3038232576  NOTICE:     Device 2
20:48:09 T:3038232576  NOTICE:         m_deviceName      : Analogue
20:48:09 T:3038232576  NOTICE:         m_displayName     : Analogue
20:48:09 T:3038232576  NOTICE:         m_displayNameExtra:
20:48:09 T:3038232576  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
20:48:09 T:3038232576  NOTICE:         m_channels        : FL,FR
20:48:09 T:3038232576  NOTICE:         m_sampleRates     : 48000
20:48:09 T:3038232576  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
20:48:09 T:3038232576  NOTICE:     Device 3
20:48:09 T:3038232576  NOTICE:         m_deviceName      : Both
20:48:09 T:3038232576  NOTICE:         m_displayName     : HDMI and Analogue
20:48:09 T:3038232576  NOTICE:         m_displayNameExtra:
20:48:09 T:3038232576  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
20:48:09 T:3038232576  NOTICE:         m_channels        : FL,FR
20:48:09 T:3038232576  NOTICE:         m_sampleRates     : 48000
20:48:09 T:3038232576  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
20:48:09 T:3038232576  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
20:48:09 T:3038232576  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
                                            <?xml version="1.0" encoding="UTF-8" ?>
                                            <advancedsettings>
                                              <network>
                                                <readbufferfactor>4.0</readbufferfactor>
                                              </network>
                                              <imageres>540</imageres>
                                              <fanartres>720</fanartres>
                                            </advancedsettings>
20:48:09 T:3038232576  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
20:48:09 T:3038232576  NOTICE: Default DVD Player: dvdplayer
20:48:09 T:3038232576  NOTICE: Default Video Player: dvdplayer
20:48:09 T:3038232576  NOTICE: Default Audio Player: paplayer
20:48:09 T:3038232576  NOTICE: Disabled debug logging due to GUI setting. Level 0.
20:48:09 T:3038232576  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
20:48:09 T:3038232576  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
20:48:09 T:3038232576  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
20:48:09 T:3038232576  NOTICE: Loaded playercorefactory configuration
20:48:09 T:3038232576  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
20:48:09 T:3038232576  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
20:48:09 T:3036689472  NOTICE: Thread ActiveAE start, auto delete: false
20:48:09 T:3028300864  NOTICE: Thread AESink start, auto delete: false
20:48:09 T:2969523264  NOTICE: Thread CRBPWorker start, auto delete: false
20:48:09 T:3038232576  NOTICE: Running database version Addons16
20:48:10 T:3038232576  NOTICE: ADDONS: Using repository repository.xbmc.org
20:48:10 T:3038232576  NOTICE: ADDONS: Using repository repository.superrepo.org.helix.all
20:48:10 T:3038232576  NOTICE: Register - new cec device registered on cec->RPI: CEC Adapter (2708:1001)
20:48:10 T:2959078464  NOTICE: Thread CECAdapter start, auto delete: false
20:48:10 T:2933912640  NOTICE: Thread PeripBusUSBUdev start, auto delete: false
20:48:11 T:3038232576  NOTICE: Raspberry PI firmware version: Dec  3 2014 17:26:22 
                                            Copyright (c) 2012 Broadcom
                                            version 23776f83288e23b6d1fc197390f79cf4cc05f558 (clean) (release)
20:48:11 T:3038232576  NOTICE: ARM mem: 384MB GPU mem: 128MB MPG2:0 WVC1:0
20:48:11 T:3038232576  NOTICE: cacheMemBufferSize: 20MB
20:48:11 T:3038232576  NOTICE: Config:
                                            arm_freq=850
                                            core_freq=375
                                            hdmi_channel_map=8
                                            disable_overscan=1
                                            program_serial_random=1
                                            config_hdmi_boost=2
                                            emmc_pll_core=1
                                            hdmi_ignore_cec_init=1
                                            hdmi_force_cec_address=65535
                                            framebuffer_ignore_alpha=1
                                            framebuffer_swap=1
                                            force_turbo=1
                                            temp_limit=85
                                            force_pwm_open=1
                                            pause_burst_frames=1
                                            avoid_fix_ts=1
20:48:11 T:3038232576  NOTICE: Config:
                                            device_tree=-
                                            device_tree_overlay=-
20:48:11 T:3038232576  NOTICE: InitWindowSystem: Using EGL Implementation: raspberrypi
20:48:11 T:3038232576  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 60.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 59.940063 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 60.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 59.940063 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 60.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 59.940063 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 59.940063 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 720 x 576 for display 0 with 720 x 576 @ 50.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 50.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 24.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 23.976025 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 25.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 30.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 29.970032 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 60.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 59.940063 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 60.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 59.940063 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1360 x 768 for display 0 with 1360 x 768 @ 60.000000 Hz
20:48:11 T:3038232576  NOTICE: Found resolution 1360 x 768 for display 0 with 1360 x 768 @ 59.940063 Hz
20:48:11 T:3038232576  NOTICE: Found (1360x768@60.000000) at 36, setting to RES_DESKTOP at 16
20:48:11 T:3038232576  NOTICE: Checking resolution 16
20:48:11 T:3038232576  NOTICE: GL_VENDOR = Broadcom
20:48:11 T:3038232576  NOTICE: GL_RENDERER = VideoCore IV HW
20:48:11 T:3038232576  NOTICE: GL_VERSION = OpenGL ES 2.0
20:48:11 T:3038232576  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
20:48:11 T:3038232576  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_APPLE_rgb_422 GL_EXT_debug_marker
20:48:12 T:3038232576  NOTICE: Running database version Addons16
20:48:12 T:3038232576  NOTICE: Running database version ViewModes6
20:48:12 T:3038232576  NOTICE: Running database version Textures13
20:48:12 T:3038232576  NOTICE: Running database version MyMusic48
20:48:12 T:3038232576  NOTICE: Running database version MyVideos90
20:48:12 T:3038232576  NOTICE: Running database version TV26
20:48:12 T:2924004416  NOTICE: Thread CECAdapterUpdate start, auto delete: false
20:48:12 T:3038232576  NOTICE: Running database version Epg8
20:48:12 T:3038232576  NOTICE: start dvd mediatype detection
20:48:12 T:2960233536  NOTICE: Thread DetectDVDMedia start, auto delete: false
20:48:14 T:3038232576  NOTICE: /home/pi/.kodi/addons/skin.eminence/sounds/sounds.xml, Line 0
                                            Failed to open file
20:48:15 T:3038232576 WARNING: JSONRPC: Could not parse type "PVR.Details.Channel"
20:48:15 T:3038232576 WARNING: JSONRPC: Could not parse type "PVR.Details.ChannelGroup.Extended"
20:48:15 T:3038232576 WARNING: JSONRPC: Could not parse type "GUI.Property.Value"
20:48:15 T:3038232576 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
20:48:15 T:2897212480  NOTICE: Thread LanguageInvoker start, auto delete: false
20:48:15 T:3038232576  NOTICE: Previous line repeats 6 times.
20:48:15 T:3038232576  NOTICE: UpdateLibraries: Starting video library startup scan
20:48:15 T:2838492224  NOTICE: Thread VideoInfoScanner start, auto delete: false
20:48:15 T:2830103616  NOTICE: Thread LanguageInvoker start, auto delete: false
20:48:15 T:3038232576  NOTICE: Previous line repeats 1 times.
20:48:15 T:3038232576  NOTICE: initialize done
20:48:15 T:3038232576  NOTICE: Running the application...
20:48:17 T:2888823872  NOTICE: -->Python Interpreter Initialized<--
20:48:17 T:2811229248  NOTICE: Previous line repeats 4 times.
20:48:17 T:2811229248  NOTICE: Thread JobWorker start, auto delete: true
20:48:18 T:3038232576  NOTICE: Previous line repeats 1 times.
20:48:18 T:3038232576  NOTICE: starting zeroconf publishing
20:48:18 T:3038232576  NOTICE: Webserver: Starting...
20:48:18 T:3038232576  NOTICE: WebServer: Started the webserver
20:48:18 T:3038232576  NOTICE: starting upnp controller
20:48:18 T:2786063424  NOTICE: Thread JobWorker start, auto delete: true
20:48:18 T:3038232576  NOTICE: starting upnp server
20:48:18 T:3038232576  NOTICE: starting upnp renderer
20:48:18 T:3038232576  NOTICE: ES: Starting event server
20:48:18 T:2685400128  NOTICE: Thread EventServer start, auto delete: false
20:48:18 T:2685400128  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
20:48:18 T:2685400128  NOTICE: UDP: Listening on port 9777
20:48:18 T:2677011520  NOTICE: Thread TCPServer start, auto delete: false
20:48:18 T:2651845696  NOTICE: Thread AirPlayServer start, auto delete: false
20:48:18 T:2838492224  NOTICE: VideoInfoScanner: Starting scan ..
20:48:18 T:2838492224 WARNING: Process directory '/home/pi/Videos/Scandal.m3u/' does not exist - skipping scan.
20:48:19 T:2838492224  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:01
20:48:20 T:2702177344  NOTICE: Thread LanguageInvoker start, auto delete: false
20:48:21 T:2897212480  NOTICE: -->Python Interpreter Initialized<--
20:48:25 T:2855269440  NOTICE: Previous line repeats 3 times.
20:48:25 T:2855269440  NOTICE: RCB Service: Start
20:48:26 T:2855269440  NOTICE: RCB Service: launch RCB on startup = false
20:48:26 T:2855269440  NOTICE: RCB Service: scrape games on startup = false
20:48:26 T:2702177344  NOTICE: -->Python Interpreter Initialized<--
20:48:26 T:2855269440  NOTICE: RCB Service: Done
20:48:26 T:2618291264  NOTICE: AxelProxy Downloader Starting - 127.0.0.1:45550
20:48:26 T:2618291264  NOTICE: Press CTL break to stop.....
20:48:26 T:2830103616  NOTICE:  StorageServer Module loaded RUN
20:48:26 T:2830103616  NOTICE: StorageClient-2.5.4 Starting server
20:48:29 T:2846880832  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting background proc (6.0.14)
20:48:29 T:2872046656  NOTICE: script.grab.fanart: Grab Fanart Service Started
20:48:35 T:2897212480  NOTICE: services: {'sys.service.avahi': 'true', 'sys.service.del': 'false', 'sys.service.tvh': 'false', 'sys.service.remote': 'true', 'sys.service.surveil': 'false', 'sys.service.ftp': 'true', 'sys.service.samba': 'true', 'sys.service.vnc': 'false', 'sys.service.boblight': 'false', 'sys.service.ssh': 'true', 'sys.service.cron': 'false', 'sys.service.sab': 'false'}
20:48:36 T:2897212480  NOTICE: enable service: avahi-daemon
20:48:36 T:2897212480  NOTICE: disable service: deluge
20:48:37 T:2897212480  NOTICE: disable service: tvheadend
20:48:37 T:2897212480  NOTICE: enable service: eventlircd
20:48:38 T:2897212480  NOTICE: disable service: surveil
20:48:40 T:2897212480  NOTICE: enable service: ftp
20:48:42 T:2897212480  NOTICE: enable service: samba
20:48:43 T:2897212480  NOTICE: disable service: vnc
20:48:43 T:2897212480  NOTICE: disable service: boblight
20:48:44 T:2897212480  NOTICE: enable service: ssh
20:48:44 T:2897212480  NOTICE: disable service: cron
20:48:44 T:2897212480  NOTICE: disable service: sabnzbd
20:48:46 T:2897212480  NOTICE: system settings from addon: {'sys.config.freq.arm': 850, 'sys.config.freq.gpu': 250, 'sys.config.freq.sdram': 400, 'sys.config.freq.core': 375, 'sys.config.freq.overvolt': 0, 'sys.config.decode.wvc1': '', 'sys.config.disable.overscan': '1', 'sys.config.decode.ac3': '', 'sys.config.freq.isp': 250, 'sys.config.decode.mpg2': '', 'sys.config.decode.dts': ''}
20:48:46 T:2897212480  NOTICE: system settings from /boot/config.txt: {'sys.config.freq.arm': 850, 'sys.config.freq.gpu': 250, 'sys.config.freq.sdram': 400, 'sys.config.freq.core': 375, 'sys.config.freq.overvolt': 0, 'sys.config.decode.wvc1': '', 'sys.config.disable.overscan': '1', 'sys.config.decode.ac3': '', 'sys.config.freq.isp': 250, 'sys.config.decode.mpg2': '', 'sys.config.decode.dts': ''}
20:50:31 T:2609902656  NOTICE: Thread LanguageInvoker start, auto delete: false
20:50:31 T:2609902656  NOTICE: -->Python Interpreter Initialized<--
20:50:32 T:2609902656  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.0) on Helix (14.1) with Python 2.7.3
20:50:32 T:2609902656   ERROR: [plugin.video.youtube] old_actions/play_video: missing video_id
20:51:12 T:2897212480  NOTICE: Thread LanguageInvoker start, auto delete: false
20:51:12 T:2897212480  NOTICE: -->Python Interpreter Initialized<--
20:51:13 T:2897212480  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.0) on Helix (14.1) with Python 2.7.3
20:51:13 T:2897212480 WARNING: [plugin.video.youtube] DEPRECATED "plugin://plugin.video.youtube/?action=play_video&videoid=aWnm-zCvTFE"
20:51:13 T:2897212480 WARNING: [plugin.video.youtube] USE INSTEAD "plugin://plugin.video.youtube/play/?video_id=aWnm-zCvTFE"
20:51:15 T:2880435264  NOTICE: Thread GUIDialogCache start, auto delete: true
20:51:16 T:3038232576  NOTICE: DVDPlayer: Opening: https://r12---sn-25g7sn7z.googlevideo.com/videoplayback?itag=18&pl=18&dur=131.448&source=youtube&expire=1430787074&mime=video%2Fmp4&requiressl=yes&ip=XXX.XXX.XXX.XX&key=yt5&mv=m&mt=1430765412&ms=au&mm=31&id=o-AElB14mr1k1PZS1_i6blC_F19hzbRoPagY-fpdN75gMk&upn=nbqNuQ4JXN4&fexp=900720%2C907263%2C916656%2C934954%2C936118%2C938028%2C9406983%2C945137%2C948124%2C952612%2C952637%2C952642%2C957201&signature=07908B9E1F5ABE8C40F904E883698CD1D2C97A25.0B0662EBC84552052F71013C4B059613399890BD&sver=3&ratebypass=yes&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&initcwndbps=676250
20:51:16 T:3038232576 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:51:16 T:2609902656  NOTICE: Thread DVDPlayer start, auto delete: false
20:51:16 T:2609902656  NOTICE: Creating InputStream
20:51:16 T:2897212480  NOTICE: Thread CMMALRenderer start, auto delete: false
20:51:17 T:2609902656  NOTICE: Creating Demuxer
20:51:17 T:2880435264  NOTICE: Thread FileCache start, auto delete: false
20:51:17 T:2609902656  NOTICE: Opening stream: 0 source: 256
20:51:18 T:2609902656  NOTICE: Creating video thread
20:51:18 T:2609902656  NOTICE: Opening stream: 1 source: 256
20:51:18 T:2855269440  NOTICE: Thread OMXPlayerVideo start, auto delete: false
20:51:18 T:2609902656  NOTICE: Creating audio thread
20:51:18 T:2643457088  NOTICE: Thread OMXPlayerAudio start, auto delete: false
20:51:18 T:2609902656  NOTICE: OMXClock using audio as reference
20:51:18 T:2855269440  NOTICE: Display resolution DESKTOP : 1360x768 (1360x768) @ 60.00 - Full Screen (16)
20:53:29 T:2609902656  NOTICE: CDVDPlayer::OnExit()
20:53:29 T:2609902656  NOTICE: DVDPlayer: eof, waiting for queues to empty
20:53:29 T:2609902656  NOTICE: Closing stream player 1
20:53:29 T:2609902656  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
20:53:29 T:2643457088  NOTICE: thread end: OMXPlayerAudio::OnExit()
20:53:30 T:2609902656  NOTICE: Closing stream player 2
20:53:30 T:2609902656  NOTICE: CDVDMessageQueue(video)::WaitUntilEmpty
20:53:30 T:2855269440   ERROR: OMXPlayerVideo: Got MSGQ_IS_ERROR(-1) Aborting
20:53:30 T:2855269440  NOTICE: thread end: video_thread
20:53:31 T:2609902656  NOTICE: Thread JobWorker start, auto delete: true
20:53:32 T:3038232576  NOTICE: Previous line repeats 2 times.
20:53:32 T:3038232576  NOTICE: CDVDPlayer::CloseFile()
20:53:32 T:3038232576  NOTICE: DVDPlayer: waiting for threads to exit
20:53:32 T:3038232576  NOTICE: DVDPlayer: finished waiting
20:53:32 T:3038232576  NOTICE: CDVDPlayer::CloseFile()
20:53:32 T:3038232576  NOTICE: DVDPlayer: waiting for threads to exit
20:53:32 T:3038232576  NOTICE: DVDPlayer: finished waiting
20:53:32 T:3036689472  NOTICE: Found 1 Lists of Devices
20:53:32 T:3036689472  NOTICE: Enumerated PI devices:
20:53:32 T:3036689472  NOTICE:     Device 1
20:53:32 T:3036689472  NOTICE:         m_deviceName      : HDMI
20:53:32 T:3036689472  NOTICE:         m_displayName     : HDMI
20:53:32 T:3036689472  NOTICE:         m_displayNameExtra:
20:53:32 T:3036689472  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
20:53:32 T:3036689472  NOTICE:         m_channels        : FL,FR
20:53:32 T:3036689472  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,24000,32000,44100,48000,88200,96000,176400,192000
20:53:32 T:3036689472  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP,AE_FMT_AC3,AE_FMT_DTS,AE_FMT_EAC3
20:53:32 T:3036689472  NOTICE:     Device 2
20:53:32 T:3036689472  NOTICE:         m_deviceName      : Analogue
20:53:32 T:3036689472  NOTICE:         m_displayName     : Analogue
20:53:32 T:3036689472  NOTICE:         m_displayNameExtra:
20:53:32 T:3036689472  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
20:53:32 T:3036689472  NOTICE:         m_channels        : FL,FR
20:53:32 T:3036689472  NOTICE:         m_sampleRates     : 48000
20:53:32 T:3036689472  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
20:53:32 T:3036689472  NOTICE:     Device 3
20:53:32 T:3036689472  NOTICE:         m_deviceName      : Both
20:53:32 T:3036689472  NOTICE:         m_displayName     : HDMI and Analogue
20:53:32 T:3036689472  NOTICE:         m_displayNameExtra:
20:53:32 T:3036689472  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
20:53:32 T:3036689472  NOTICE:         m_channels        : FL,FR
20:53:32 T:3036689472  NOTICE:         m_sampleRates     : 48000
20:53:32 T:3036689472  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
20:53:35 T:2702177344  NOTICE: Thread LanguageInvoker start, auto delete: false
20:53:35 T:2702177344  NOTICE: -->Python Interpreter Initialized<--
20:53:37 T:2702177344  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.0) on Helix (14.1) with Python 2.7.3
20:54:13 T:2643457088  NOTICE: Thread LanguageInvoker start, auto delete: false
20:54:13 T:2643457088  NOTICE: -->Python Interpreter Initialized<--
20:54:15 T:2643457088  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.0) on Helix (14.1) with Python 2.7.3
20:54:23 T:2702177344  NOTICE: Thread LanguageInvoker start, auto delete: false
20:54:23 T:2702177344  NOTICE: -->Python Interpreter Initialized<--
20:54:25 T:2702177344  NOTICE: [plugin.video.youtube] Running: YouTube (5.1.0) on Helix (14.1) with Python 2.7.3

**Comment by bromix** [comment]
Please paste the log on pastebin.com or similar and provide the link.

**Comment by derf974** [comment]
http://pastebin.com/mSVDJqdd

**Comment by derf974** [comment]
Sorry for disturbing, an update solved the problem.

**Comment by bromix** [comment]
No problem :)
