### ISSUE TITLE
Display more than 50 items at a time

### ISSUE THREAD

**Issue by CrazyCoder** [bromix/plugin.video.youtube#265]
Sometimes it's not convenient to browse multiple pages, especially when you have a lot of channels (browsing to a channel with name Z in the list can take 10 or more pages).

There was a fork for the old YouTube plug-in that supported up to 500 items on a page: https://github.com/jmbreuer/youtube-xbmc-plugin .

Would be really great if this plug-in supported it as well. Thank you for considering.

**Comment by bromix** [comment]
https://developers.google.com/youtube/v3/docs/
The new APIv3 only supports up to 50 items per page (after that the pagination starts). I don't start to trigger additional calls to deplete the quota of the addon to display 500 items or more (and most fo the people only work the first 20 ;) )
If the quota is depleted I have to buy new one or the addon shuts down by google. So I have to shape the calls to a minimum as possible.

I wish I could help...maybe I find another solution in one of the updates so the quota wouldn't suffer.

**Comment by Dukobpa3** [comment]
I think it may be autoload of the next page without a click ;)

**Comment by bromix** [comment]
@Dukobpa3 this could/would be a feature of KODI :)

**Comment by CrazyCoder** [comment]
Another option would be to allow users to specify their own application ID (and register it with google) in advanced plugin settings so that power users can use their own quota. The option to load more than 50 items can be enabled only if user has specified his own application ID.

**Comment by Dukobpa3** [comment]
> this could/would be a feature of KODI :)

I'm not sure.
Provider gives content to Kodi and Kodi just shows it to user. If provider don't gives more than 20 items - so kodi can't to show it.

**Comment by bromix** [comment]
But the provider can return an item with corresponding attributes, if reached, so KODI knows to trigger the next page call ;)

**Comment by Dukobpa3** [comment]
Sure ;)

**Comment by bromix** [comment]
I like to keep the issue-tracker clean and organized. I close this issue, because it's more of a cosmetic issue and I've more important issue to attend to :(
