### ISSUE TITLE
Render channel icon as an overlay on video thumbnails

### ISSUE THREAD

**Issue by CrazyCoder** [bromix/plugin.video.youtube#266]
At the moment it's really hard to identify which channel has uploaded a video when browsing through the new subscription videos (you have to open a menu for that).

When using the old plug-in, I wrote a proxy that was fetching new subscription videos and modifying video thumbnail by adding a small channel icon on the top left.

This worked really well and it was very easy to identify which video came from which channel when browsing the new subscription videos.

It would be really great if this feature can be implemented directly in this plugin. As it may consume additional resources, it should be optional and disabled by default.

Examples:

![gog channel](http://i.imgur.com/ltGqYwz.jpg)

![gamespot](http://i.imgur.com/zESbDU3.jpg)

**Comment by bromix** [comment]
How should I do that?! I don't start image processing with python. If this is possible without third-party vendors this would be optional nice but I don't see how. Provide me an example in python and I think about it :)

**Comment by CrazyCoder** [comment]
I guess there is a limitation on the libraries you can use? If you could bundle Python Imaging Library with your plug-in, it would be very easy, they have many examples how it can be done.

If it's not an option, just detect/ask user for the path to imagemagick installation. This can be done via the command line utilities, then you will cache the rendered image and display it instead of the original one. Examples with imagemagick command line: http://raspi.tv/2014/overlaying-text-and-graphics-on-a-photo-and-tweeting-it-pt-5-twitter-app-series .

**Comment by bromix** [comment]
ähm no...this will result banning the addon from the official repo and that's not my plan ;)

**Comment by CrazyCoder** [comment]
What about command line imagemagick? User can install it on Linux with one command and on Windows with a simple installer. Then plug-in can either detect it automatically or ask user to specify the path to the installation, then you just call the binary with appropriate parameters and get the image.

There is no need to distribute anything with your addon.

**Comment by bromix** [comment]
These are dirty hacks in programming I don't understand or support as a product manager. Either do it right or leave it ;) I don't start cluttering the addon/my work. Everyone can feel free to fork the addon and add this kind of feature.

I think this should makes more sense as a feature of KODI and a skin. An addon is only the content provider, nothing more.

**Comment by CrazyCoder** [comment]
Fine, how about https://github.com/ojii/pymaging ? Open source, pure Python.

**Comment by bromix** [comment]
Can't publish because of license conflict/trouble.

License: BSD (some files have other licenses, see LICENSE.txt)

**Comment by bromix** [comment]
Don't get me wrong here. I like the idea.

But we have also to take in account to processing time for at least 50 items. On a RASP, OSMC, PLEX, Fire TV, etc, this will be slow based on processing time, because the images have to be download first (for each item 2 images => image of the video and the channel logo, processed and then cached via KODI).

I try to ask the devs of KODI, maybe some skins support a channel logo via the **setArt** method for an item.

**Comment by CrazyCoder** [comment]
Fair enough. I guess I'll try to make it as a service that will give the modified thumbnail for the original one. Only one URL will be changed in the forked YouTube plug-in then.

Support from the skin would be great.

**Comment by bromix** [comment]
I talked to some of the devs. and one designer. They agree that this is more the work of a skin (if the information are provided). Therefore I close this issue.

One question: The addon shows the fanart in the background of the channel for each video you select. This is why I don't  really saw an issue with this. Additionally the name of the channel is in the description (top).
