### ISSUE TITLE
Playlist: play all order by [default|reverse|shuffle]

### ISSUE THREAD

**Issue by TheWizIL** [bromix/plugin.video.youtube#267]
Hi,

Bromix you do great work. Thank you.

In my plugin i use:
plugin://plugin.video.youtube/playlist/[PID]/

It will be nice if in right-click menu will be option to play all video in list order by [default|reverse|shuffle].

Thank U.

TheWiz

**Comment by bromix** [comment]
For playlists this is already implemented. If you select play all, or from herer you will be asked to select an order.

**Comment by TheWizIL** [comment]
[IMG]http://i59.tinypic.com/2vjsr9g.jpg[/IMG]

Did i miss something? can't see this option.

**Comment by bromix** [comment]
Are you directly in a playlist or the channels feed?

**Comment by TheWizIL** [comment]
yes.

i use this: plugin://plugin.video.youtube/playlist/[PID]/

**Comment by bromix** [comment]
As soon as you select play all you will be asked for an order.

**Comment by TheWizIL** [comment]
I don't have an option of "play all".
