### ISSUE TITLE
Can't play some videos because "This video may be inappropriate for some users"

### ISSUE THREAD

**Issue by ricardograca** [bromix/plugin.video.youtube#268]
Whenever I try to playback videos that have been flagged as "inappropriate" Kodi fails to do so with an error message saying that "This video may be inappropriate for some users".

This happens even if I am logged into my Youtube account.

**Comment by bromix** [comment]
Have you set your age correct?

**Comment by ricardograca** [comment]
Now I have, the year was missing :D I could swear I had already done that some time ago. Sorry for the bogus issue, but maybe it will help others with the same problem.

**Comment by bromix** [comment]
;)

**Comment by gilgil87** [comment]
i have the same problem,
i singed in.
my age is set in mt profile and still i cant reach videos on kodi-youtube

**Comment by ricardograca** [comment]
I had this problem again recently, and I was also signed in and the age set correctly. What I did to "solve" the problem was to open the affected video in my PC where it showed the warning about the video potentially being "inappropriate", I clicked the option to continue anyway and after that I no longer got the error on Kodi.
