### ISSUE TITLE
Exception in ContentProvider Unknown kind ''

### ISSUE THREAD

**Issue by Queuecumber** [bromix/plugin.video.youtube#270]
I am getting the above error when I click on the "Subscriptions" menu item. I think its linked to 5.1.1 (although it was working fine last night and only stopped working this morning)

Screenshot of error: http://imgur.com/CfACwrU

Let me know if I can provide you with additional information

**Comment by Queuecumber** [comment]
Just confirmed that downgrading to 5.1.0 this issue does not occur

**Comment by bromix** [comment]
Complete debug log please. Without it I can't help. Log only via pastebin.com or similar and complete not only parts of it.

**Comment by Queuecumber** [comment]
Sure here is the full debug log

http://pastebin.com/CSSAgx1y

**Comment by bromix** [comment]
Okay...your're running Isengard...can you sign out and re-login. I changed the API-KEYs with v5.1.1 (see change log).

Each major version of KODI has it's own API KEY so I have more control over the quota.

**Comment by Queuecumber** [comment]
Confirmed, re-logging in fixes the issue, thanks!

**Comment by logisex** [comment]
re-login didn't fix the issue for me...

**Comment by bromix** [comment]
Complete debug log please. Without it I can't help. Log only via pastebin.com or similar and complete not only parts of it.
