### ISSUE TITLE
Subscriptions Channel Video List View Mode Doesn't Persist

### ISSUE THREAD

**Issue by Mad-Halfling** [bromix/plugin.video.youtube#271]
There seems to be a problem with the video playlist view mode within the subscriptions section.  If I go into [Subscriptions] from the main menu, and change View type to Thumbnail, then exit and return to that are, this setting/mode persists, fine.
If I then go into a particular channel, on that menu, to view the video list and change the View to Thumbnail this displays the list as thumbnails, correctly.
But, if I then go back up one menu level, and then down again into that same channel, it starts to display the videos in thumbnail mode, with placeholders for the thumbnails, but then it changes back to View: List mode.  If I manually change back to thumbnail mode, this works OK, but only as long as I stay at that menu level.
This did work a while ago, though I can't remember how long (sorry, I've been meaning to report this bug for a while)

Recreation steps:
- Load the addon, whilst logged in to an account that is subscribed to some channels
- From the main menu (on my system, this is set up in Thumbnail mode, too) enter the Subscriptions menu (this is also set to view in Thumbnail mode, on my system)
- Enter a channel
- Change the View to Thumbnail, using the left sidebar menu
- Go up one menu level
- Go back into the channel

The video list will briefly attempt to show in thumbnail mode, but will then revert to List.
This also exhibits in Big List mode, and similarly from the My Subscriptions menu option, from the root menu.

I am running the addon version 5.1.1
I am running it on RaspBMC, the Kodi version from the log is
NOTICE: Starting Kodi (14.1 Git:2015-02-02-81c4046-dirty). Platform: Linux ARM 32-bit
NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)

**Comment by bromix** [comment]
Disable the override for the view via the addon settings.

**Comment by Mad-Halfling** [comment]
Sorry for the delay, I missed the update e-mail.  Yes, that fixed the issue, sorry if I missed it mentioned somewhere, it seemed like a bug as the behaviour didn't replicate at the previous level.  Thanks for your time, and a great addon

**Comment by bromix** [comment]
No problem ;)
