### ISSUE TITLE
Don't show more than 50 subscriptions

### ISSUE THREAD

**Issue by LeMusch** [bromix/plugin.video.youtube#272]
I just noticed that I can just scroll to my first ~50 subscriptions. Yesterday everything worked fine and I was able to see the last one.

**Comment by bromix** [comment]
You updated from 4.4.X to 5.X.X?

**Comment by bromix** [comment]
Okay I see. There is a bug. I hope it's not a problem of Google/YouTube

**Comment by bromix** [comment]
Nothing I can do....Google/YouTube broke there own API. They aren't returning the next page token. Without it I can request the next results.

**Comment by sobkas** [comment]
Bug: https://code.google.com/p/gdata-issues/issues/detail?id=7163

**Comment by bromix** [comment]
Thanks @sobkas

**Comment by sobkas** [comment]
There is a workaround for this problem: http://stackoverflow.com/questions/30263293/youtube-subscriptions-list-api-v3-nextpagetoken-isnt-available/30263572#30263572

**Comment by bromix** [comment]
Won't work properly - see the last answer. You have different tokens based on the max amount of items you want to see.

**Comment by sobkas** [comment]
there should be a way to predict the nextPageToken without needing a response from server

**Comment by bromix** [comment]
No time for predictions here, only facts and results ;)

**Comment by sobkas** [comment]
So I have poked around and got this table of tokens:
First number is max number of results
1,CAEQAA,CAIQAA,CAMQAA,CAQQAA,CAUQAA,CAYQAA
2,CAIQAA,CAQQAA,CAYQAA,
3,CAMQAA,CAYQAA
So it's easy to see that every second token from maxresults=1 is a valid token of maxresults=2, and every third one of maxresults=3, so with full(or big enough) list of tokens for maxresults=1 you can generate every token up to maxresults=50

**Comment by bromix** [comment]
I don't start generating tokens for a bug which is the problem of the API :)

**Comment by sobkas** [comment]
Well I already did a hack that is in a "workish" condition. And with a way to generate specific tokens without need for server it could be used like start-index.

**Comment by sobkas** [comment]
Still broken...

**Comment by JohnnyBluRay** [comment]
I am curious, just how long does something like this take for Google to repair?

**Comment by sobkas** [comment]
Will you use pagetokengenerator if I port this one to python? https://gist.github.com/pulsar256/f5621e85ef50711adc6f

**Comment by bromix** [comment]
If I have the example in python I would take a look at it :)

**Comment by sobkas** [comment]
So there is one: https://gist.github.com/sobkas/df718622ea5ff15c23eb
first number is a page number, second one is maxresults

**Comment by sobkas** [comment]
if overflow >= 2:
        token_1 += 8
should be 1 instead of 2

**Comment by sobkas** [comment]
Patch: https://gist.github.com/sobkas/b4f819409e321d35e875
It almost works, but:
1. First page is displayed 2 times, for some reason
2. It's set to 50 maxresults, there should be a way to fix it(is there a way to access number of results inside response_to_items?) didn't have time to check it myself

So what you think?

**Comment by bromix** [comment]
Looks good so far. Naming convention is a little bit off (sorry :) )
If I find some time in the week I try to use your code. I will need to write some test cases first...without it, new function or features won't get included in my addons ;) but thanks for the conversion to python...hopefully this will compensate the bug by Google.

**Comment by sobkas** [comment]
"Naming convention"?

**Comment by bromix** [comment]
"gen_token" "strange_numbers" "maxs" ;)

In my kind of work as PM I would have to return the project to my co-worker :)

But the rest looks fine.

**Comment by sobkas** [comment]
It was a wip so I just slapped any name that was better than "asdf", "return 'NOIDEA'" might be a hint. Also I had to re tokens again because I had a bit of hard time with that code I have linked

**Comment by bromix** [comment]
No harm done :) I appreciate your work. Thanks.

**Comment by sobkas** [comment]
I'm glad that you posted your code into that bugrapport, my code was ugly as sin.
Also sorry for burdening you with fixing my lazy code...

**Comment by bromix** [comment]
No problem. I needed testcases first to see if both snippets are working correctly and there weren't. So I wrote my own routine based on the JS snippet.
