### ISSUE TITLE
Youtube crashing on OSMC/RaspberryPi, 1080p not working

### ISSUE THREAD

**Issue by marank** [bromix/plugin.video.youtube#280]
For two days now, Youtube crashes occasionally. Mostly if I want to exit a running video by pressing stop, and sometimes if I want to rewind or fast-forward. Logfile: http://pastebin.com/34VnpnAd

Edit: Additional crashlog after pressing the rewind button: http://pastebin.com/MXuumRdg

On the other hand, it seems I can't get 1080p working. I've set up Youtube to always use 1080p (addon settings), but when I press the info button while viewing a video, it always says 720p (I now the video does have a 1080p version).

**Comment by bromix** [comment]
Not a problem of the addon. Please inform a developer of your KODI version.

ERROR: OMXPlayerVideo: Got MSGQ_IS_ERROR(-1) Aborting

Seems to be some kind of message queue.

And for 1080p...read the documentation. KODI doesn't support DASH and therefore no 1080p videos.
