### ISSUE TITLE
Documentation Addition Request

### ISSUE THREAD

**Issue by CMcBooster** [bromix/plugin.video.youtube#281]
Do views using this add-on count toward YouTube analytics?

**Comment by bromix** [comment]
? I don't understand what you mean.

**Comment by CMcBooster** [comment]
If I watch a video using your add-on does it count as a view (as far as you are aware) according to YouTube's system.

**Comment by bromix** [comment]
It should count as a view (based on a test with some private videos). But feel free to test yourself ;)
