### ISSUE TITLE
Show video rating

### ISSUE THREAD

**Issue by gwiazdorrr** [bromix/plugin.video.youtube#289]
Being able to see the rating (likes vs dislikes) would be a great time saver, especially in the search result view.

I think it used to be visible in the search results on youtube.com, but they got rid of it. However, there are Chrome (https://chrome.google.com/webstore/detail/ratings-preview-for-youtu/cgbhdenfmgbagncdmgbholejjpmmiank) and Firefox (https://addons.mozilla.org/pl/firefox/addon/youtube-ratings-preview/) extensions that bring this functionality back.

**Comment by bromix** [comment]
As for the APIv3 these are separated calls for each video and cost a lot of quota. Sorry I would love to provide these additional information, but Google has done a terrible job with the new API :(
