### ISSUE TITLE
More instead of Next page?

### ISSUE THREAD

**Issue by sobkas** [bromix/plugin.video.youtube#291]
I was thinking that "Next Page" is very tedious in almost all scenarios. What do you think about "More" that will extend current list of items with content that would normally showed on the next page? Right now "Next page" just killing me, especially on subscriptions list(I would prefer to display the whole list and use a more aggressive caching to reduce number of queries.)

**Comment by bromix** [comment]
Technically not possible. With the call of the 'next page' I don't know what was on the page before. We would have to write/store/cache all items to disk and load them afterwords, again and again. That's to much to work on and not worth the effort and my time. On some device this would take even to much time to re-read the data from before (e.g someone has 500 subscriptions, the UX with this addon would suffer on the other side).

**Comment by sobkas** [comment]
Technically? It would only take extending kodis xbmcplugin.endOfDirectory with option like keepPrevious(bool, set to true to keep content of the list) that can be used with updateListing=True

**Comment by bromix** [comment]
Code this extension in a fork of KODI and create a PR so we all benefit from it. This doesn't belong here as long as such an option is missing in the core implementation.

**Comment by sobkas** [comment]
For now I have opened a thread on kodis forum http://forum.kodi.tv/showthread.php?tid=229785 , as I hope someone with more familiarity of its codebase will implement it. But right now I think that best way is to extend CFileItemList and expose it trough endOfDirectory.
