### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by testman42** [bromix/plugin.video.youtube#292]
I use latest Kodi with this plugin and from what I can tell, this thing can't play youtube playlists. It can search for playlists and even see what videos are in one playlist, but it can only play one video from the playlist. It does not autoplay next one, neither do |< and >| buttons work to navigate to previous/next video on playlist.

Anything that can be done about that?

**Comment by testman42** [comment]
OK, I explored a bit and found out that only after I bring up additional options, I get "play from here" and "play all" options. I think that "Play from here" should be default option on video select.
After selecting one of those two optins, buttons |< and >| start to work.

I just think that this addon could be a bit more context aware.
If I am looking at playlist, I probably want to play the whole thing, not just one video from it.

**Comment by bromix** [comment]
I understand, but what should the addon do? The context menu is part of the whole UX. An addon can't change the playback behavior of KODI. You have to change the setting here => http://kodi.wiki/view/Settings/Videos#Playback

**Comment by testman42** [comment]
OK, thank you.

And thank you for fast response.
