### ISSUE TITLE
Only 50 subscribtions visible/useable

### ISSUE THREAD

**Issue by Gehirnfussel** [bromix/plugin.video.youtube#296]
Hi,
I got this strange problem with this nice youtube addon:
Only 50 of the (117) channels I subscribed to are shown (in 'My Subscriptions' and 'Subscriptions').
I tried to log out and log back in but this didn't helped.

Using KODI 15.x b2 and YouTube Plugin 5.1.6 on an FireTV

**Comment by bromix** [comment]
This is an API restriction. I can only request 50 items per page. But you should see a 'Next page' item at the bottom of the list. If not please check if you're G+ account is connected to YouTube.

**Comment by Gehirnfussel** [comment]
Yes, my G+ account is connected to YouTube.
And 'next page' only gives me 50 in total - there is no 2nd page.
(I have the "Items per page" set to 50)

**Comment by bromix** [comment]
I hope everything is working so far? To clean up stuff I will close this issue, but reopen if there is still a problem.

**Comment by Gehirnfussel** [comment]
Yes, you can keep this close. It was my fault 😪
I have multiple youtube accounts on one gmail account and I had the wrong channel (with exactly 50 subscriptions).
Damn it! 😓
