### ISSUE TITLE
SSL via CCurlFile broken with Raspbian Jessie

### ISSUE THREAD

**Issue by raspbiannewbie** [bromix/plugin.video.youtube#301]
Updated my Raspberry Pi 2 to Raspbian Jessie. Now i cannot open YT-Videos in Kodi (Helix) anymore.
Error message in kodi.log:
 NOTICE: [plugin.video.youtube] Running: YouTube (5.1.6) on Helix (14.2) with Python 2.7.9
 ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for https://[huge_url_following]

Several websites pointing to RC4 cipher problem in urllib.
Maybe the following forum thread is similar to this:
http://forum.kodi.tv/showthread.php?tid=192119

Installed curl components :
 curl,libcurl3:armhf and libcurl3-gnutls:armhf     7.38.0-4+deb8u2
 python-pycurl   7.19.5-3

Please tell me which further info i should provide if needed.

**Comment by bromix** [comment]
A full debug log would be nice...and not posted in here...use pastebin.com or similar. Also I think this is a repeating problem of RasPi (again). They miss sometimes to compile ffmpeg or curl with https support.
But first let me take a look at a complete debug log.

**Comment by raspbiannewbie** [comment]
Hello and thanks for the quick reply :-)

Log file is up at
http://pastebin.com/Pnpg06MG
Trying to check if https support is compiled into my versions of ffmpeg and curl right now but i am no expert and this can take a while. Sorry.
Btw: if it is a repeating mistake of especially raspi-built packages, maybe there is a way to implement a check-routine that tests SSL support before using it (if not too complicated).

**Comment by bromix** [comment]
Can you also enable 'debugging' in the system for more information in the log.

**Comment by raspbiannewbie** [comment]
New log created at http://pastebin.com/hKh43N4X
Sorry again!

**Comment by bromix** [comment]
That's strange...the addon itself is using https, that's how you get all the meta-data...so this works...but won't work is the playback of the stream via KODI. So I would say the problem is somewhere in the distro. If you're using a proxy, please try to disable the proxy.

**Comment by raspbiannewbie** [comment]
Before updating to Jessie it worked fine for me. i updated today and so i can guarantee that no changes in my network are done/responsible.
No proxy is used and all other addons are working, too. Maybe some of them are'n using SSL but i doubt they all don't.
I temporarly installed BestOfYoutube.com addon. Worked flawless, too.

**Comment by bromix** [comment]
That makes no sense. BestOfYouTube triggers this YouTube addon to play the videos. BestOfYouTube is only a manager.

But you said it worked before...so something in the distro must have changed.

**Comment by raspbiannewbie** [comment]
I will have a deeper look into it tomorrow. If i cannot pin it down i'll just restore my backup and forget about it :/
If i can find out something i'll let you know. Thanks for your help!
