### ISSUE TITLE
Script failed with v5.1.7

### ISSUE THREAD

**Issue by brianwoo** [bromix/plugin.video.youtube#307]
Hi there,

When I try to open the Add-on, I get a "script failed" error.  This seems to happen if a user has been authenticated.  If there is no user setup, the Add-on does not return this error.

Anything I can do to help solve this issue?

Thanks,
Brian

**Comment by bromix** [comment]
Some kind of a debug log via pastebin.com or similar would be help full ;)

**Comment by brianwoo** [comment]
Thanks for your reply.  It turns out there was a corruption in the Add-on's database.  I deleted its data and re-ran the Add-on and the problem went away.
