### ISSUE TITLE
1080p Stream does not work (max 720p)

### ISSUE THREAD

**Issue by iz8mbw** [bromix/plugin.video.youtube#318]
Hi.
I'm using the last version of the plugin on OpenELEC 5.0.8 (Kodi 14.2) on a Raspberry Pi 2.
When I would like to watch 1080p stream from YouTube the video stream is always 720p and so not 1080p.

**Comment by bromix** [comment]
Already explained ;)
https://github.com/bromix/plugin.video.youtube/wiki/Missing-or-Broken#1080p
