### ISSUE TITLE
Mark video as unwatched after it has been watched

### ISSUE THREAD

**Issue by tv21** [bromix/plugin.video.youtube#319]
In other parts of Kodi, such as in movies, there is a way to mark something as unwatched once you have watched it.  An exception is the YouTube video addon, where there is currently no way to mark a YouTube video as unwatched once it has been watched.  Please include that capability in a future release.

**Comment by bromix** [comment]
Press "w"
Addons have no context support like movies or tv shows. These would be an issue in KODI core
