### ISSUE TITLE
EXCEPTION IN CONTENTPROVIDER

### ISSUE THREAD

**Issue by aimikept** [bromix/plugin.video.youtube#320]
I got this error when i clicked "Popular right now"
EXCEPTION IN CONTENTPROVIDER
Unknown kind "

YouTube Version: 5.1.8
Kodi 15.1
OS: Ubuntu 14.04.3 LTS
I have already sign-in & sign-out (vice versa) but still received the same error.
Appreciate all the help, info & guide. Thank you

**Comment by bromix** [comment]
Duplicate #288
