### ISSUE TITLE
Watch Later: Problem with Context Menu After Playing A Video

### ISSUE THREAD

**Issue by dhanar10** [bromix/plugin.video.youtube#321]
I often add videos to Watch Later, then watch it on my Kodi HTPC. I have disabled "remove video after playing from watch later" option because I don't want a video that I played automatically removed from the list. Here where I start notice the issue.

After, I have finished playing a video and go back to Watch Later list. I opened context menu on that video and I cannot find "Remove" command. Then, when I tried to move to other video on the list and open context menu, "Remove" command is there.

Workaround that I found: If I cannot find "Remove" from context menu, I move to other video on the list, open context menu and select "Refresh". Then I go back to the video that I want to remove, open context menu, and the "Remove" command is there. It works every time but it is a bit annoying.

**Comment by bromix** [comment]
This seems to be a problem in KODI because I've no control after the playback of the context menu. Please file an issue in KODI directly.
