### ISSUE TITLE
Non-English description marked as English

### ISSUE THREAD

**Issue by MilhouseVH** [bromix/plugin.video.youtube#322]
https://github.com/bromix/plugin.video.youtube/blob/master/addon.xml#L27

Presumably this is responsible for the non-English description, seen here:
http://addons.kodi.tv/show/plugin.video.youtube/

![screenshot](http://i.imgur.com/aDpTStj.jpg)

**Comment by bromix** [comment]
ahh...this should be Bulgarian (bg)...somehow the translator missed that (copy&paste) I think :)
thanks for the hint.
