### ISSUE TITLE
Assistance with Modification

### ISSUE THREAD

**Issue by dozyh** [bromix/plugin.video.youtube#324]
Would you be willing to help me make a modification to your addon? I download some videos for later viewing, and I'd like to have the existing interface useable to play the downloaded files to save myself bandwidth. That'd involve checking for the filename (YouTube's video ID since it's unique) and passing its URL to Kodi instead of YouTube's URL.

**Comment by bromix** [comment]
duplicate #140 #107 #37

**Comment by dozyh** [comment]
Hmm not a duplicate. I'm downloading the videos with an external program and want to check the location on disk for a file, not download within the plugin.

**Comment by dozyh** [comment]
Bump

**Comment by bromix** [comment]
Seriously? I won't have time for the next couple of days because of a surgery. So be patient...this is not so important at the moment.

**Comment by dozyhh** [comment]
Well considering people have complained about the underlying issue for six years yeah clearly I deserve the "You're a bad person because you're being impatient," treatment.

Hope your surgery is uneventful.

**Comment by MartijnKaijser** [comment]
@dozyh go fuck yourself

**Comment by dozyhhh** [comment]
That response doesn't even make sense dude.
