### ISSUE TITLE
Video info displays (1x1) instead of the channel name since Kodi 14.1 update

### ISSUE THREAD

**Issue by CrazyCoder** [bromix/plugin.video.youtube#328]
Start playing a video, open now playing overlay. Above the video title, where the channel name was previously displayed, you now have the useless (1x1) for all videos which represents Season/Episode.

Makes no sense for YouTube playlist videos. Channel name would be much more useful.

**Comment by bromix** [comment]
That's a problem of the skin how the information ate processed

**Comment by CrazyCoder** [comment]
Do you mean that plug-in has no way to override whatever the skin displays for the channel name?

**Comment by CrazyCoder** [comment]
I found a fix, comment out the lines which don't set season/episode to 1 if there is no one extracted from the video. Now the skin displays channel name.

https://github.com/bromix/plugin.video.youtube/blob/master/resources/lib/youtube/helper/utils.py#L168

**Comment by bromix** [comment]
Correct!...an addon is only a data provider (much data as possible). The skin is responsible how to display these information.

**Comment by CrazyCoder** [comment]
See my last comment with the trivial fix.

**Comment by bromix** [comment]
Your fix won't work for all skins.

**Comment by CrazyCoder** [comment]
99% of the users are using the default Confluence skin. I don't think it would do anything bad for 1% of the other users.

**Comment by bromix** [comment]
As a team member I can say you're wrong. The stats tell a different story.

**Comment by CrazyCoder** [comment]
What's the reason to hardcode season and episode to 1 if this information is not relevant for the video?

If you leave it undefined, skin handles it correctly and displays channel name instead.

If some skin would fail because the video doesn't specify season/episode, it's a bug in that skin that should be fixed.

**Comment by bromix** [comment]
It's not hardcoded....later I try to extract season and episode via regex. Fork the addon try to correct it in your way. I will continue my recovery from surgery.

**Comment by CrazyCoder** [comment]
I see what you are doing later, but in case you can't extract anything via regex, it's essentially hardcoded to `1` instead of being left undefined, which would be the logical behavior, IMO.

I hope you recover soon. Please consider removing the 2 lines which hardcode season/episode to `1`. This will restore the original behavior of YouTube plug-in which has been there for years, makes more sense and provides relevant information for the video instead of the cryptic `(1x1)`.

**Comment by bromix** [comment]
Done...this will result now in that ;) The problem with most skins is...the skins don't validate if season or episode information are available...so it looks always wrong. But I don't care anymore :P
![image](https://cloud.githubusercontent.com/assets/4136891/9989700/207ea97e-605b-11e5-8461-38215c763a9e.png)
