### ISSUE TITLE
Option to limit/sort search results by time

### ISSUE THREAD

**Issue by probonopd** [bromix/plugin.video.youtube#329]
It would be a killer feature if one could limit search results to show only videos uploaded today, this week, this month etc., like in the official YouTube app. Also it would be great of search results could be ordered by the date, so that the videos uploaded most recently would show up first.

For me it is unclear how I am supposed to find the most recent videos on topic X in the current version.

**Comment by bromix** [comment]
I mark this as duplicate #97 It's a similar one. The search could do a lot more, but it will cost me a lot of quota, which will disable the addon on a daily basis. I've to do more optimizations for that. The addon has simply too many users :)
