### ISSUE TITLE
Cannot Reproduce LIVE videos on raspberry pi

### ISSUE THREAD

**Issue by bbrandolin** [bromix/plugin.video.youtube#336]
hello,

        I have installed Kodi 15.1 isengard in diferent systems, my problem is that I cant view live videos on raspberry pi. The same video at the same time, I could view Kodi over windows7.

       I tried diferent LIVE videos, but I don´t have lucky in raspberry pi.

       Have you any suggesstions ?

       Do you need more info ?.

Youtube bromix plugin: 5.1.9

Regards
Bernardo

**Comment by bromix** [comment]
YouTube uses TS-streams for live streams which are not well or not at all supported by the KODI for Raspi. Please contact a developer of the Raspi distribution. Also keep in mind, if it should work but you see a message that live streams are not allowed in your country, then that's so :(
