### ISSUE TITLE
DASH support?

### ISSUE THREAD

**Issue by wp9015362** [bromix/plugin.video.youtube#337]
@bromix :

FFmpeg seems to properly support DASH now in conjunction with youtube-dl, see the following posts over there:

http://forum.kodi.tv/showthread.php?tid=237356&pid=2148409#pid2148409

So, would there be any chance you could implement DASH support in your YouTube add-on now?

Regards

**Comment by jansiegel** [comment]
If this would allow 1080p playback, I'm all for it.

**Comment by wp9015362** [comment]
> @jansiegel wrote:
> 
> If this would allow 1080p playback, I'm all for it.

Not just 1080p, but also 2160p and 60fps :wink:.

**Comment by bromix** [comment]
duplicate #72, #139, #256
