### ISSUE TITLE
Add surround support

### ISSUE THREAD

**Issue by marksand** [bromix/plugin.video.youtube#339]
The plugin does not deliver surround (5.1) audio streams from videos that have them (like this one: https://www.youtube.com/watch?v=PqVCPE8_ntE) and only gives stereo output

Using RPi2 with OpenElec

**Comment by bromix** [comment]
There is no 5.1 stream available via common YouTube videos.

**Comment by marksand** [comment]
@bromix I do not understand, the movie I gave in the link provides this stream. I can hear the surround if I manually download it to the PC and play via kodi

**Comment by bromix** [comment]
Read the comments below of the video you provided. YouTube videos do not have 5.1 channel streams. You will only hear a surround up-mix via your AV.
