### ISSUE TITLE
Some videos don't play

### ISSUE THREAD

**Issue by honyczek** [bromix/plugin.video.youtube#341]
After updating OpenELEC to version 6.0.0 (Kodi 15.2), some videos are not played. Kodi tries to connect streaming, then appears bubble Working and then nothing happens.

The same problem described @Scooby-2 at https://github.com/dirkjanm/firefox-send-to-xbmc/issues/28 :
>    I have been using this addon for some while and I love it. But as of today on Linux Mint 17 Qiana running Firefox 42.0 sending to kodi 15.2, the vast majority of youtube videos fail to play on Kodi. This one plays: https://www.youtube.com/watch?v=372436tJiaM
>    This one doesn't: https://www.youtube.com/watch?v=-qaB-sxDZwU
>    No errors are reported but I do get the "Sending to Kodi" and "Sent to Kodi - success" messages on the PC. All I get on Kodi is the usual "Opening stream" box and, if it is at the main menu, the play controls slide in, a small box flashes up in the lower right corner saying "working" and then the controls slide out again. Nothing else happens and there is nothing in the dmesg log.
>    All VEVO videos that I have tried fail to send and it seems that only very old standard Youtube videos can be sent.

**Comment by bromix** [comment]
Please test update 5.1.10 and confirm that it's working again.

**Comment by heroandroid** [comment]
I just tried 5.1.10 and it is not working. I specifically tried vevo videos.

**Comment by heroandroid** [comment]
Started working just now. Muat have been another issue.
