### ISSUE TITLE
Continuous play without keyboard?

### ISSUE THREAD

**Issue by Dreim3r** [bromix/plugin.video.youtube#342]
Hello.
I have a problem playing playlists on Youtube. 
It plays only one song and then doesn't go to the next one. I dont want to downgrade the Add-On to an older Version and cant use the "'c' -> 'Play All'"-Way because I dont use a keyboard - just an remote control on the OpenElec.

Any help would be appreciated!
Thank you!

**Comment by bromix** [comment]
Without context menu not possible. Use a proper remote. I can call the context menu even with my remote.
