### ISSUE TITLE
Fanart Quality

### ISSUE THREAD

**Issue by Tolriq** [bromix/plugin.video.youtube#352]
@bromix Hello :)

Is it normal that fanart.jpg in \resources\media is low quality blurred one ?

The main addon one is clear and good.

I'm adding support for some things and will display fanart but the blurred one looks like crap :(

**Comment by bromix** [comment]
Than provide a better one and stop complaining...the fanart is from YouTube/tv

**Comment by Tolriq** [comment]
@bromix  Really ? You get in the team and now gives shitty answers likes that ? 

I ask a simple question, if it's normal than the 2 fanart are different, maybe there's a reason for the blur.

Do you see any complaining, I don't so please avoid such stupid answer, specially when asking me to provide a fanart that you already have and use .....

Reading : https://github.com/bromix/plugin.video.youtube/commit/16b116603bce71b0d75281f431677e7969e56da5 I suppose the blur is wanted so I have my answer.

But never thought you'd become like that ..... The time about resolving url addon seems sounds far away .....

**Comment by bromix** [comment]
@Tolriq I think I'm done with maintaining the addon...the constant demanding and complaining about whats wrong and how should it be, is getting on my nerves. Not only by you, also by other users....thanks for it...didn't know you had an opinion about me...didn't asked for it and I don't case. We are not friends.

**Comment by Tolriq** [comment]
You really need some holidays ... I never asked for anything and was always in proper discussion asking for your thought and never ordering you or complaining.

Next time go pass your nerves on someone else as I was always respectful with you this have nothing to do with being friends but how to act with peoples .....

**Comment by bromix** [comment]
You're really rude. Me my decision is final.

**Comment by Tolriq** [comment]
As a final word, I'm far from rude I'm still respectful and did not expected you to treat me or anyone else like that for a simple question. But your answers were rude and indeed affected me since I was clearly not prepared for that from you.

Question that could have a simple answer like yes it's normal see PR XXX .....

Anyway have a nice day and hope your nerves goes down a little so you can enjoy Christmas and New Year.
