### ISSUE TITLE
Can't play the following youtube videos

### ISSUE THREAD

**Issue by finalmakerr** [bromix/plugin.video.youtube#353]
6gwBBEw-l5E
kV3ig8sMur0
uzh96OclEQM
oCezgzbCZBk
t-L-GTRyJtI
YcOQdRCm58k

**Comment by bromix** [comment]
Sorry, but I accept only PRs, because I stop maintaining the add-on at the end of the year.

**Comment by finalmakerr** [comment]
That's a bad news for us :(
Respect and love to you!
