### ISSUE TITLE
Download/Cache a video

### ISSUE THREAD

**Issue by bromix** [bromix/plugin.video.youtube#37]

**Comment by robwebset** [comment]
I have created a pull request for downloading videos:
https://github.com/bromix/plugin.video.youtube/pull/274

Hope this is OK!

Rob

**Comment by bromix** [comment]
cleanup

**Comment by uNiversaI** [comment]
Has this been implemented yet?

**Comment by bromix** [comment]
nope, but I clean up my issues, because I'm preparing the dev. for version 6.X.X

**Comment by uNiversaI** [comment]
Sure but isnt this a valid request then?

**Comment by bromix** [comment]
valid maybe, but not so much requested.

**Comment by uNiversaI** [comment]
thers been at least 5 requesters 2 of which tried PR and failed the others probably cant even be bothered to report bugs
