### ISSUE TITLE
External call to play a playlist

### ISSUE THREAD

**Issue by bromix** [bromix/plugin.video.youtube#56]
plugin://.../playlist/?method=play&playlist_id=35345

or

plugin://.../play/?playlist_id=35345

I like the last one, because it's almost the same like playing a video 

plugin://.../play/?video_id=35345

**Comment by bromix** [comment]
Already resolved with #27

**Comment by superryo** [comment]
great job bromix.  is there a way to force play mode (default, random, reverse) when you make the external call?

**Comment by bromix** [comment]
See my answer in the forum ;)
